name: "[Infra] Task"
description: CI/CD, 배포, 설정 변경 등
title: "[Infra] "
labels: ["area:infra", "type:chore", "status:needs-triage"]
body:
  - type: textarea
    id: work
    attributes:
      label: 작업 내용
      description: 무엇을 바꾸고/추가할지
      placeholder: 예) Actions 캐시 추가, 빌드 매트릭스, Dockerfile 수정
  - type: textarea
    id: impact
    attributes:
      label: 영향 범위
      description: 어느 서비스에 영향? 다운타임? 권한/시크릿 필요?
  - type: textarea
    id: plan
    attributes:
      label: 롤아웃/롤백 플랜
